version: "3.8"

services:
  bot:
    build: .
    command:
      - python main.py
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - app_net

  db:
    image: postgres:12-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db_name
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app_net

networks:
  app_net: