version: "3.8"

services:
  bot:
    build: .
    command:
      - python main.py
    env_file:
      - .env
    depends_on:
      - db


  db:
    image: postgres:12-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db_name
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data:
